# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#passing-parameters

trigger:
- master

variables:
  MKL_NUM_THREADS: 1
  NUMEXPR_NUM_THREADS: 1
  OMP_NUM_THREADS: 1
  VML_NUM_THREADS: 1
  OPENBLAS_NUM_THREADS: 1
  PYTHONHASHSEED: 0 # Ensure tests are correctly gathered by xdist
  SETUPTOOLS_USE_DISTUTILS: "stdlib"

jobs:
- template: ci/azure_template.yml
  parameters:
    name: Linux
    vmImage: ubuntu-20.04

- template: ci/azure_template.yml
  parameters:
    name: Windows
    vmImage: windows-2019
