# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

parameters:
  # defaults for any parameters that are not specified
  name: ''
  vmImage: ''


jobs:

- job: ${{ parameters.name }}Test
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      python37_legacy:
        python.version: '3.7'
        NUMPY: 1.17.5
        SCIPY: 1.3.3
        PANDAS: 0.25.3
        STATSMODELS: 0.10.2
        XARRAY: 0.13
      python38_mid:
        python.version: '3.8'
        NUMPY: 1.18.5
        SCIPY: 1.4.1
        PANDAS: 1.0.5
        STATSMODELS: 0.11.1
        XARRAY: 0.14.1
        XXHASH: true
      python38_recent:
        python.version: '3.8'
        NUMPY: 1.19.4
        SCIPY: 1.5.4
        PANDAS: 1.1.5
        STATSMODELS: 0.12.1
        XARRAY: 0.15.1
        test.install: true
      python39_no_cython:
        python.version: '3.9'
        SETUP_OPTIONS: '--no-binary'
      python39_latest:
        python.version: '3.9'
    maxParallel: 10

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
    displayName: 'Use Python $(python.version)'

  - script: |
      python -m pip install --upgrade pip setuptools wheel
      source ci/install-posix.sh
      python -m pip install -r requirements.txt
      python -m pip install -r requirements-test.txt
      python -m pip install -r requirements-dev.txt
      jupyter kernelspec list
    displayName: 'Install dependencies'

  - script: |
     flake8 linearmodels
     black --check linearmodels
     isort --check linearmodels
    displayName: 'Check style and formatting'

  - script: |
      python -m pip list
    displayName: 'List Configuration'

  - script: |
      echo "Installing to site packages"
      python setup.py bdist_wheel ${SETUP_OPTIONS}
      WHL=$(ls -t dist)
      pip install ./dist/${WHL}
    displayName: 'Install linearmodels (site-packages)'
    condition: eq(variables['test.install'], 'true')

  - script: |
      if [ -z ${SETUP_OPTIONS} ]; then
        echo python -m pip install -e . -v --no-build-isolation
        python -m pip install -e . -v --no-build-isolation
      else
        echo python setup.by develop ${SETUP_OPTIONS}
        python setup.py develop ${SETUP_OPTIONS}
      fi
    displayName: 'Install linearmodels (editable)'
    condition: ne(variables['test.install'], 'true')

  - script: |
      echo "Testing site packages"
      mkdir test_run_dir
      pushd test_run_dir
      python -c "import linearmodels; linearmodels.test(['-n', 'auto', '--junitxml=../junit/test-results.xml'])"
      popd
    displayName: 'Run tests (site-packages)'
    condition: eq(variables['test.install'], 'true')

  - script: |
      echo "Testing editable install"
      if [[ ${COVERAGE} == "true" ]]; then
        export COVERAGE_OPTS="--cov-config .coveragerc --cov=linearmodels --cov-report xml:coverage.xml --cov-report term"
      fi
      echo pytest -m "${PYTEST_PATTERN}" --junitxml=junit/test-results.xml -n auto --durations=25 ${COVERAGE_OPTS} linearmodels/tests
      pytest -m "${PYTEST_PATTERN}" --junitxml=junit/test-results.xml -n auto --durations=25 ${COVERAGE_OPTS} linearmodels/tests
    displayName: 'Run tests (editable)'
    condition: ne(variables['test.install'], 'true')

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
    condition: and(eq(variables['coverage'], 'true'), ne(variables['test.install'], 'true'))

  - bash: bash <(curl -s https://codecov.io/bash)
    displayName: 'CodeCov upload'
    condition: and(eq(variables['coverage'], 'true'), ne(variables['test.install'], 'true'))
